name: Publish

on:
  push:
    branches:
    - main

jobs:
  gh-pages:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
        
    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - name: Generate Site
      run: |
        swift build
        publish generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./Output
          publish_branch: master
